name: Build Android APK with Docker

on: [push]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build APK with Docker
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        workdir: .
        cache: 'true'

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: photo_geo-apk
        path: bin/*.apk
