name: Build Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04 # Используем более стабильную версию Ubuntu
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git openjdk-11-jdk
        sudo apt install -y libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf automake libtool pkg-config
        sudo apt install -y unzip zip curl
        
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade Cython==0.29.36
        pip install --upgrade buildozer
        # Устанавливаем конкретные версии для стабильности
        pip install kivy==2.1.0
        pip install python-for-android==2023.3.10
        
    - name: Configure buildozer
      run: |
        # Создаём базовый buildozer.spec
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi
        
        # Настраиваем buildozer.spec для более стабильной сборки
        echo "[app]" > buildozer.spec
        echo "title = PhotoGeo" >> buildozer.spec
        echo "package.name = photo_geo" >> buildozer.spec
        echo "package.domain = org.example" >> buildozer.spec
        echo "" >> buildozer.spec
        echo "source.dir = ." >> buildozer.spec
        echo "source.include_exts = py,png,jpg,kv,atlas,txt" >> buildozer.spec
        echo "" >> buildozer.spec
        echo "version = 0.1" >> buildozer.spec
        echo "requirements = python3,kivy==2.1.0" >> buildozer.spec
        echo "" >> buildozer.spec
        echo "[app]" >> buildozer.spec
        echo "android.permissions = CAMERA,ACCESS_FINE_LOCATION,WRITE_EXTERNAL_STORAGE" >> buildozer.spec
        echo "" >> buildozer.spec
        echo "[buildozer]" >> buildozer.spec
        echo "log_level = 2" >> buildozer.spec
        echo "android.accept_sdk_license = True" >> buildozer.spec
        echo "android.api = 31" >> buildozer.spec
        echo "android.minapi = 21" >> buildozer.spec
        echo "android.ndk = 25b" >> buildozer.spec
        echo "android.arch = arm64-v8a" >> buildozer.spec
        
    - name: Build APK with specific settings
      run: |
        # Очищаем кэш перед сборкой
        buildozer android clean || true
        
        # Запускаем сборку с подробным логированием
        buildozer --verbose android debug
        
    - name: Check if APK was created
      run: |
        # Проверяем наличие APK
        if ls bin/*.apk 1> /dev/null 2>&1; then
          echo "APK успешно создан!"
          ls -la bin/
        else
          echo "APK не найден, но проверим другие возможные местоположения..."
          find . -name "*.apk" -type f 2>/dev/null || echo "APK файлы не найдены"
        fi
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: photo_geo-apk
        path: |
          bin/*.apk
          *.apk
