name: Build Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04 # Используем более стабильную версию Ubuntu
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git openjdk-11-jdk
        sudo apt install -y libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf automake libtool pkg-config
        
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade Cython==0.29.36
        pip install --upgrade buildozer
        
    - name: Configure buildozer
      run: |
        # Создаём базовый buildozer.spec
        buildozer init
        # Настраиваем buildozer.spec для более стабильной сборки
        sed -i 's/android.api = 27/android.api = 31/' buildozer.spec
        sed -i 's/android.minapi = 21/android.minapi = 21/' buildozer.spec
        sed -i 's/android.ndk = 19b/android.ndk = 25b/' buildozer.spec
        sed -i 's/android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec
        
    - name: Build APK with retry
      run: |
        # Повторяем попытку сборки до 3 раз в случае ошибки
        for i in {1..3}; do
          echo "Попытка сборки #$i"
          if buildozer android debug; then
            echo "Сборка успешна!"
            break
          else
            echo "Попытка #$i не удалась, очистка и повтор..."
            buildozer android clean || true
            if [ $i -eq 3 ]; then
              echo "Все попытки сборки неудачны"
              exit 1
            fi
            sleep 30
          fi
        done
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: photo_geo-apk
        path: bin/*.apk
