name: Build Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git openjdk-11-jdk
        sudo apt install -y libffi-dev libssl-dev libjpeg-dev zlib1g-dev autoconf automake libtool pkg-config
        sudo apt install -y unzip zip curl
        
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade Cython==0.29.36
        pip install --upgrade buildozer==1.5.0
        pip install kivy==2.1.0
        
    - name: Create buildozer.spec
      run: |
        cat > buildozer.spec << 'EOF'
[app]
title = PhotoGeo
package.name = photo_geo
package.domain = org.example

source.dir = .
source.include_exts = py,png,jpg,kv,atlas,txt

version = 0.1
requirements = python3,kivy==2.1.0

[app]
android.permissions = CAMERA,ACCESS_FINE_LOCATION
android.api = 31
android.minapi = 21
android.ndk = 25b
android.arch = arm64-v8a

[buildozer]
log_level = 2
android.accept_sdk_license = True
EOF
        
    - name: Build APK
      run: |
        # Принудительно принимаем лицензии
        echo "y" | sdkmanager --licenses >/dev/null 2>&1 || true
        # Запускаем сборку с таймаутом
        timeout 60m buildozer android debug || true
        
    - name: Check for APK
      run: |
        echo "=== Checking for APK files ==="
        find . -name "*.apk" -type f 2>/dev/null || echo "No APK files found"
        echo "=== Contents of bin directory ==="
        ls -la bin/ 2>/dev/null || echo "bin directory not found"
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: photo_geo-apk
        path: |
          bin/*.apk
          *.apk
        if-no-files-found: ignore
